### ISSUE TITLE
Unable to install on MacOS

### ISSUE THREAD

**Issue by ismyhc** [megamarc/Tilengine#11]
Hi,
Im having trouble installing on my mac. I've cloned the repo and have SDL2.framework install at: /Library/Frameworks/SDL2.framework

I tried this command:
```
Tilengine (master) $ ./sudo install
bash: ./sudo: No such file or directory
```

Then this:
```
Tilengine (master) $ sudo sh install
Installing Darwin x86_64
mkdir: /usr/lib/x86_64-linux-gnu: Operation not permitted
cp: /usr/lib/x86_64-linux-gnu: Operation not permitted
mkdir: /usr/lib/x86_64-linux-gnu/cmake/Tilengine: Operation not permitted
install: line 35: /usr/lib/x86_64-linux-gnu/cmake/Tilengine/tilengine-config.cmake: No such file or directory
mkdir: /usr/lib/x86_64-linux-gnu/pkgconfig: Operation not permitted
install: line 37: /usr/lib/x86_64-linux-gnu/pkgconfig/tilengine.pc: No such file or directory
chmod: /usr/lib/x86_64-linux-gnu/Tilengine.dylib: No such file or directory
```

Any ideas? :)

**Comment by ismyhc** [comment]
I was able to copy Tilengine.dylib to user/local/lib and after that the samples compiled:

`cp darwin_x86_64/Tilengine.dylib /usr/local/lib/`

**Comment by ismyhc** [comment]
I compiled the c samples, but when running get something like this:

![screen shot 2017-11-07 at 4 42 00 pm](https://user-images.githubusercontent.com/840551/32519438-c133453e-c3da-11e7-838a-c040b9f51a73.png)

**Comment by megamarc** [comment]
I checked the install script and I think that paths `/usr/lib/x86_64-linux-gnu` should be changed to `/usr/local/lib/` older versions of OSX allowed writing to /usr/lib/x86_64-linux-gnu, that's the default library path, but in newer versions someone told me that this feature was removed and only /usr/local/lib is allowed. I don't know if this path is in the search list by default. I test the builds inside a virtual machine with OSX 10.11 Mountain Lion and the script works just fine. Some experienced OSX guy/girl should edit the script to make it work on newer versions

**Comment by megamarc** [comment]
The compiled C programs aren't finding the graphic assets. They should be run inside the same "c" folder where the source code is, that's in the same level as the "assets" path

**Comment by megamarc** [comment]
I've checked the samples and you're right, the assets aren't found even if they're in the right folder. Something must broke in the last release because it was working before. I've to fix it then

**Comment by megamarc** [comment]
It's working right, it's something mac specific launching the program from the GUI. Instead open a terminal window, navigate to the `tilengine/samples/c` folder and run somet
hing by hand, for example `./shooter` I don't know why it doesn't work from the GUI.
![mac_os](https://user-images.githubusercontent.com/14149983/32520204-7895464e-c40f-11e7-8708-11097d796a01.jpg)

**Comment by ismyhc** [comment]
@megamarc ah, yes running from terminal works as expected. Thank you! Digging in soon. :)

**Comment by LordStephen77** [comment]
TileEngine is a unique library! I grew up with Nes and SNes I love TileEngine. But I would like a good guide to integrate TileEngine into Codeblocks (Linux). Work on the documentation (currently the documentation is incomplete but well done). Many examples mostly play Mario style Platformer, and @megamarc Shooter Xenon style (Amiga, the first Xenon).

Thanks for this nice project, I do my best to solve the initial problems in the hope that they will be corrected soon.

**Comment by megamarc** [comment]
@LordStephen77 Thanks for your comments and suggestions. The best place for help request are the official forums, so othe members can benefit from the responses:
http://www.tilengine.org/forum/index.php
