### ISSUE TITLE
Unable to build Tilengine

### ISSUE THREAD

**Issue by Lucas-Marcel** [megamarc/Tilengine#116]
I'm trying to build tilengine with mingw make32 but i'm getting these errors.
[ 46%] Built target Tilengine
[ 48%] Linking C executable Test.exe
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lc: No such file or directory
collect2.exe: error: ld returned 1 exit status
mingw32-make[2]: *** [CMakeFiles\Test.dir\build.make💯 Test.exe] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:155: CMakeFiles/Test.dir/all] Error 2
mingw32-make: *** [Makefile:90: all] Error 2

**Comment by megamarc** [comment]
Hi Marcel,
I don't use mingw64 for building, so I cannot give support for this tool. You have two options:
* build with Visual Studio Community 2017 or later
* download a prebuilt version from itch.io for a small donation: https://megamarc.itch.io/tilengine
