### ISSUE TITLE
Access violation error with more than 6 tilesets

### ISSUE THREAD

**Issue by danielgholmes** [megamarc/Tilengine#120]
Hi Marc,

If there are tiles in a map from more than 6 different tilesets, it causes an access violation error most of the time. Sometimes a tile will be replaced with a tile from a different tileset which further confirms that there seems to be a memory access issue.

Here is an example which should help to reproduce the issue [layers_test.zip](https://github.com/user-attachments/files/16303023/layers_test.zip)

Using Tilengine v2.15.2

**Comment by megamarc** [comment]
Hi Daniel! How are you doing?I'm spending a week on holidays outside without my laptop. I'll take a look at the issue next week when I'll come back.Regards,El 19 jul. 2024 8:35, Daniel Holmes ***@***.***> escribió:
Hi Marc,
If there are tiles in a map from more than 6 different tilesets, it causes an access violation error most of the time. Sometimes a tile will be replaced with a tile from a different tileset which further confirms that there seems to be a memory access issue.
Here is an example which should help to reproduce the issue layers_test.zip
Using Tilengine v2.15.2

**Comment by megamarc** [comment]
The "Tile" structure that holds each tile in a tilemap allocates 3 bits for the tileset, so up to 8 tilesets can be used in a single layer. Seems that the condition is unchecked, so the app crashes when bypassing the limit. The example you posted has 15 tilesets attached an 9 are used on a single layer

**Comment by danielgholmes** [comment]
Thanks for clarifying. I doubt we would need more than 16 tilesets in a single layer in the future, but even so, we will make sure to adhere to that limit.
