### ISSUE TITLE
why binaries are paid

### ISSUE THREAD

**Issue by RoTob123** [megamarc/Tilengine#122]
like why there's binaries and they cost, but there's also a source code which is free

+[this game (apotris)'s pc builds are using tilengine!](https://akouzoukos.com/apotris)

**Comment by megamarc** [comment]
Hi!

Tilengine is open source and you can use as you fit. Prebuilt binaries are just a convenience for people struggling with gathering dependencies and building the binaries themselves. They're also a way of "donating" and supporting hosting fees. But they're totally optional.

Is Apotris using Tilengine? Cool!
