### ISSUE TITLE
Any plans to port to WASM?

### ISSUE THREAD

**Issue by gulagkulak** [megamarc/Tilengine#123]
Seems like the perfect library for making games that run inside a modern web browser.

**Comment by megamarc** [comment]
I have a private development branch that compiles to wasm with emscripten. I have to work on some small details, but it's almost complete.

At this moment it just compiles original C samples to wasm, to run inside the browser. Should anybody write a decent javascript wrapper, it could be used to write games directly in javascript.

Here some examples of it already running:

https://www.tilengine.org/emcc/platformer.html
https://www.tilengine.org/emcc/mode7.html
https://www.tilengine.org/emcc/shooter.html
https://www.tilengine.org/emcc/shadow.html

Use cursor keys to move, and z to shoot
