### ISSUE TITLE
Missing CWF_NEAREST window flag in C# bindings (possibly others)

### ISSUE THREAD

**Issue by turbohz** [megamarc/Tilengine#17]
I just realised that the value is missing in the enum to set the window flags.

Can submit a pull request with that fixed.

**Comment by turbohz** [comment]
I see there's a closed issue reporting just the same. I don't know the reason it was closed, though.

**Comment by megamarc** [comment]
The C# binding isn't updated to the latest version of the library. The CWF_NEAREST flag was recently added to the C source. The closed source refers to the feature in the core library. The C# binding still needs to be updated.

**Comment by megamarc** [comment]
The C# binding was updated to library 1.19 in the last commit 😃

**Comment by turbohz** [comment]
Awesome!
