### ISSUE TITLE
Renaming python directory

### ISSUE THREAD

**Issue by knight-corvi** [megamarc/Tilengine#2]
There is an error with the installation file under linux. 
It complains about not being able to find the python directory.
A simple change inside the bash script to upper case 'P' should do the job.
```bash
cp python/*.py $target
```
to
```bash
cp Python/*.py $target
```

**Comment by megamarc** [comment]
This one is a bit tricky. In my development computer, the folder name is "python" in lowercase, but for some reason in GitHub repository it appears capitalized as "Python. If I try the command **git mv Python python**, it says that I don't have permission.
