### ISSUE TITLE
Won’t Work with latest version of SDL2 

### ISSUE THREAD

**Issue by Rubberduckycooly** [megamarc/Tilengine#21]
Firstly, This looks amazing and just what i was looking for! I planned to use this as a graphics engine and use SDL as the core engine, however when I try to add tilengine to my project, I get “error: uint_t redefinition” and it won’t compile. 

I have tried everything and nothing seems to work, including removing SDL2 from my project but the issue there is that some of the scripts in my project require functions of SDL2 that I don’t know how/can’t replicate in tilengine, so that doesn’t work either.

**Comment by megamarc** [comment]
Thanks for your comment! Tilengine uses internally SDL2 so there isn't any inherent incompatibility between them. It seems related to standard type definitions around line 60 in Tilengine.h (different compilers had different support for C99 types). Please post here what's your target platform, C/C++ compiler, and SDL2 release.

**Comment by Rubberduckycooly** [comment]
I use SDL v2.0.8, my project is currently targeting windows and I use visual studio community 2017 as my compiler. Hope this helps!

**Comment by megamarc** [comment]
I can't reproduce this issue. I used VisualStudio 2017 Community to create a simple C project, using Tilengine 1.19 and SDL2 2.0.8. The following code builds without any issue in both x86 and x64 platforms:

```
#include "SDL.h"
#include "Tilengine.h"

int main(int argc, char* argv[])
{
	int frame = 0;

	SDL_Init(SDL_INIT_VIDEO);
	TLN_Init(400, 240, 2, 1, 0);
	TLN_CreateWindow(NULL, 0);
	while (TLN_ProcessWindow())
	{
		TLN_DrawFrame(frame);
		frame += 1;
	}
	TLN_Deinit();
	SDL_Quit();
	return 0;
}
```
Can you build this snippet in your project?

**Comment by Rubberduckycooly** [comment]
[SDLTLN_test.zip](https://github.com/megamarc/Tilengine/files/1974494/SDLTLN_test.zip)

firstly, sorry for taking a while, other things got in the way. Anyways i tried to create a test project to see if that snippet of code would work, but i had no luck, and got this error again:
"Error	C2371	'int8_t': redefinition; different basic types	SDLTLN_test	c:\vs_dev_lib\tilengine\include\win32\tilengine.h	(line) 61"

i have included the project with this post, to help you diagnose and fix this issue.
