### ISSUE TITLE
Unable to install (Fedora 28)

### ISSUE THREAD

**Issue by wmellema** [megamarc/Tilengine#27]
During installation: It fails with the following error message:
```
[wmellema@localhost Tilengine] $ sudo ./install
Installing Linux x86_64
mkdir: cannot create directory ‘/usr/lib/x86_64-linux-gnu’: Not a directory
./install: line 35: /usr/lib/x86_64-linux-gnu/cmake/Tilengine/tilengine-config.cmake: Not a directory
mkdir: cannot create directory ‘/usr/lib/x86_64-linux-gnu’: Not a directory
./install: line 37: /usr/lib/x86_64-linux-gnu/pkgconfig/tilengine.pc: Not a directory
chmod: cannot access '/usr/lib/x86_64-linux-gnu/libTilengine.so': Not a directory
```

**Comment by megamarc** [comment]
Hello,
It seems that Fedora uses a different path than Debian-based distros for storing user libraries. I've to figure out how to retrieve at runtime the suitable path. In the meantime, if you know what path is it, you can modify install.sh and replace the '/usr/lib/x86_64-linux-gnu' path for the correct one.

**Comment by megamarc** [comment]
Support for non-debian distros relate to generic issue #33
