### ISSUE TITLE
Samples failing to execute

### ISSUE THREAD

**Issue by pmprog** [megamarc/Tilengine#30]
I have a fresh install of Debian 9 (running in VirtualBox), followed the readme instructions: installed your dependencies (along with mono-complete), ran "make" and "install", and all seemed to go fine.

Following that I went into /samples/csharp, and ran "msc *.cs" to compile the Platformer.exe (which was fine), however, running it yields an unhandled exception:
```
System.NullReferenceException: Object reference not set to an instance of an object
  at (wrapper managed-to-native) Tilengine.Tilemap.TLN_LoadTilemap(string,string)
  at Tilengine.Tilemap.FromFile (System.String filename, System.String layername) [0x00000] in <7575f3660863472cbab376510af7a113>:0 
  at Platformer.LoadLayer (Tilengine.Layer layer, System.String filename) [0x00000] in <7575f3660863472cbab376510af7a113>:0 
  at Platformer.Main (System.String[] args) [0x00063] in <7575f3660863472cbab376510af7a113>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
  at (wrapper managed-to-native) Tilengine.Tilemap.TLN_LoadTilemap(string,string)
  at Tilengine.Tilemap.FromFile (System.String filename, System.String layername) [0x00000] in <7575f3660863472cbab376510af7a113>:0 
  at Platformer.LoadLayer (Tilengine.Layer layer, System.String filename) [0x00000] in <7575f3660863472cbab376510af7a113>:0 
  at Platformer.Main (System.String[] args) [0x00063] in <7575f3660863472cbab376510af7a113>:0 
```

So I went into the /samples/c folder and ran "make", and they all compiled without a problem, but running them all give
`Segmentation fault`

Can't really understand why it's actually failing

**Comment by megamarc** [comment]
What CPU version is your Debian? 32 or 64 bit?
I have just basic experience with Debian, because my build and test environment is Lubuntu. Maybe some global library paths are different, that's a inherent problem of the very fragmented linux ecosystem. There is a Fedora issue with similar problems...
Tell me the exact Debian version so I can setup a virtual machine and test it to see what happens.

**Comment by pmprog** [comment]
According to the system info inside the VM, most of this is probably irrelevant to you.

OS Version: Debian 9.5 (x86-64)
Cinnamon Version: 3.2.7
Linux Kernel 4.9.0.6-amd-64
Processor: Intel Core i7-3770 CPU @ 3.40GHz x 1
Memory: 1GiB
Graphics Card: InnoTek Systemberatung GmbH VirtualBox Graphics Adapter (prof-if 00 [VGA controller])


It's a bit odd really, I did a bit more playing, and I can run one example: /samples/c/mouse_test (though it is unresponsive... I'm wondering if the VM just isn't going to be sufficient to run this stuff anyway). It even loads the Mario graphic; but if I load "barrel" in gdb:
```
(gdb) run
Starting program: /home/debian/code/Tilengine/samples/c/barrel 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
__strcasecmp_l_avx () at ../sysdeps/x86_64/multiarch/strcmp-sse42.S:164
164	../sysdeps/x86_64/multiarch/strcmp-sse42.S: No such file or directory.

```

**Comment by everyfan** [comment]
I have a similar issue on Manjaro Linux (which is based on Arch Linux). I've gotten the code to compile and install, but it crashes every time I try to run a sample, in either Python or C, with "Segmentation fault (core dumped)". I'm also running in VirtualBox.

**Comment by everyfan** [comment]
I think this might be a larger issue with compilation on some Linux systems.

**Comment by everyfan** [comment]
I just tired it with the prebuilt 64bit linux build from itch.io, rather than building from the latest Git, and had the same result.

**Comment by everyfan** [comment]
And, just tried it again on real Manjaro Linux hardware (not in VirtualBox) -- same issue.

**Comment by megamarc** [comment]
@everyfan your issue is not the same than @pmprog one:

- He has problems with the C# binding on a supported Debian OS.
- You have problems installing the native library on an unsupported non-debian OS.

Your issue has already been answered and solved in the Manjaro forums for another user that had the same problem (but I wasn't aware of until now):
https://forum.manjaro.org/t/is-usr-lib-x86-64-linux-gnu-a-directory-tilengine-installation-problem/47357

Please read the issue #33 and the related Facebook note about non-debian distros. I'm sorry about this issue but I don't know how to manage many incompatible distros that have different install paths.

I hope that following the forum post you'll be able to run the samples!

**Comment by everyfan** [comment]
I'm so sorry to trouble you then! My apoligies

**Comment by everyfan** [comment]
@megamarc I've just tried writing a custom SDL2 program in C, and am haveing the same Segmentation fault error! I've looked into it, and it looks like a bug with some versions of SDL2 on Arch Linux. https://github.com/OpenRCT2/OpenRCT2/issues/6364

**Comment by vaclavbenes** [comment]
Hi , I have similar problem with seg fault. 

```
(gdb) run
Starting program: /usr/bin/python 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Python 3.7.0 (default, Jul 15 2018, 10:44:58) 
[GCC 8.1.1 20180531] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tilengine as tln
>>> engine = tln.Engine.create(400, 240, 1, 0, 20)
>>> engine.set_load_path("../assets/sonic")
>>> foreground = tln.Tilemap.fromfile("Sonic_md_fg1.tmx")

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7effc09 in __strcasecmp_l_sse42 () from /usr/lib/libc.so.6

```
Tested with arch linux 4.18.6
```
pacman -Q sdl2
sdl2 2.0.8-9

```
i tried different versions of sdl2, but i ve got same problem.

**Comment by pmprog** [comment]
Okay, I tried this on a Windows PC, and it segfaults on the DrawFrame function with unauthorised memory access (bad pointers?); but I have also tried this on a Mint 17, and it runs fine.

**Comment by megamarc** [comment]
Just fixed the segmentation fault in last commit https://github.com/megamarc/Tilengine/commit/f9d130e349bdab71ed81875d36416a00821dd09d. Caused by stock strdup() inside the simplexml.c module, replaced by a custom mystrdup()
