### ISSUE TITLE
Install doesn't work on Manjaro Linux

### ISSUE THREAD

**Issue by everyfan** [megamarc/Tilengine#32]
Builds fine, but when I run install as sudo it gives the errors:

Installing Linux x86_64
mkdir: cannot create directory ‘/usr/lib/x86_64-linux-gnu’: Not a directory
./install: line 35: /usr/lib/x86_64-linux-gnu/cmake/Tilengine/tilengine-config.cmake: Not a directory
mkdir: cannot create directory ‘/usr/lib/x86_64-linux-gnu’: Not a directory
./install: line 37: /usr/lib/x86_64-linux-gnu/pkgconfig/tilengine.pc: Not a directory
chmod: cannot access '/usr/lib/x86_64-linux-gnu/libTilengine.so': Not a directory

**Comment by megamarc** [comment]
Support for non-debian distros relate to generic issue #33
