### ISSUE TITLE
Installing on non-debian linux

### ISSUE THREAD

**Issue by megamarc** [megamarc/Tilengine#33]
Tilengine is only guaranteed to install and run on Ubuntu-based distros, and possibly any Debian-based one (Ubuntu is a Debian derivative and they share path tree).

Please read this full facebook note:
https://www.facebook.com/notes/tilengine/about-linux-support/1858448714191067/

If you want your distro to be supported, please extend the install.sh script (or rework the Makefile) and make a pull request with the upgrade.

**Comment by preemeijer** [comment]
It is working on OpenSUSE Tumbleweed. Thanks for your hard work.
