### ISSUE TITLE
TLN_GetErrorString() Crashes C# apps

### ISSUE THREAD

**Issue by Rubberduckycooly** [megamarc/Tilengine#35]
Whenever TLN_GetErrorString() is called the application immediatly closes with no error or anything, this happens in my project and both C# samples, and it makes Debugging really annoying as even the slightest issue crashes my game with no error codes, so I can't find out what I need to fix...

**Comment by megamarc** [comment]
What version of .NET/Mono are you targeting? I usually worked with 2.0 and it behaves well, but I recently discovered that .NET versions 4.x don't handle returning strings in the same way, crashing the application everytime. This is happening in other projects not related to Tilengine, that worked in previous versions of .Net but crash with current one. I don't know why.

**Comment by megamarc** [comment]
Fixed in CsTilengine binding commit https://github.com/megamarc/CsTilengine/commit/b8467ab6c897170511706123f17793fddf2608b1
Strings from/to unmanaged code were handled the wrong way, but the crash was only apparent sometimes.
