### ISSUE TITLE
Mega Drive/Genesis style sprite masking

### ISSUE THREAD

**Issue by ToruTheRedFox** [megamarc/Tilengine#49]
Would it be possible to (optionally) emulate this feature of the YM7101 VDP?https://s3unlocked.blogspot.com/2017/11/vdp-sprite-masking.html

**Comment by LBPPlayer7** [comment]
It could be implemented in a way where you set the mask's Y position and height instead of the weird way the YM7101 does it.

**Comment by megamarc** [comment]
Sprite masking feature added in release 2.7.0. Check TLN_SetSpritesMaskRegion() and TLN_EnableSpriteMasking() functions.
