### ISSUE TITLE
Missing libTilengine.so for linux 64 bit

### ISSUE THREAD

**Issue by davideGiovannini** [megamarc/Tilengine#5]
Could you please add the 64 bit version of the library?

**Comment by megamarc** [comment]
I could if I had it :-) seriously, I don't have experience building for linux 64. I build from a 32-bit Lubuntu with multiarch gcc and I can compile basic 64-bit programs with the -m64 switch. But it complains about missing files, like the *zconf.h* header and *libSDL2.so* shared library, that are found when compiling the same tests in 32-bit mode. Something with search path settings. However some files are actually found, like the SDL2 headers... Any help will be appreciated so I can release a 64-bit build.

**Comment by davideGiovannini** [comment]
I don't have much experience either, but I can try :) I'm setting up a 32bit ubuntu virtual machine to try it. In the meantime maybe you could post  the error you're getting (at least the part with the libraries name).

**Comment by megamarc** [comment]
Thanks for your help davide. You won't be able to build tilengine itself because the sources are not public, but as long as we manage to compile this simple source, I'll be able to build the whole project:
```
#include <stdio.h>
#include <SDL2/SDL.h>
#include <png.h>

int main (int argc, char* argv[])
{
	printf ("Hello world\n");
	SDL_Init (SDL_INIT_VIDEO);
	SDL_Quit ();
	return 0;
}
```
and build with
`gcc main.c -o main -m64 -lpng -lSDL2`

This is the console output:
```
In file included from /usr/include/png.h:540:0,
                 from main.c:3:
/usr/include/zlib.h:34:19: fatal error: zconf.h: No existe el archivo o el directorio
 #include "zconf.h"
                   ^
/usr/bin/ld: no se puede encontrar -lpng
/usr/bin/ld: no se puede encontrar -lSDL2
collect2: error: ld returned 1 exit status
```
As you can see, it complains about not finding the "zconf.h" source and png and SDL2 shared libraries. The same source builds ok in 32-bit mode, just replacing the `-m64` switch with `-m32`

**Comment by davideGiovannini** [comment]
I almost got it working, following [this](https://wiki.debian.org/Multiarch/HOWTO#Usage).

    dpkg --add-architecture amd64
    apt-get update
    apt-get install libpng-dev:amd64

Now when I compile with `m64` at least it finds libpng, but I'm having problems installing the 64 bit version of SDL2 `libsdl2-dev:amd64`.

I will try again later :)

**Comment by megamarc** [comment]
Good point adding amd64 architecture :+1: However, after trying to install **libpng12-dev:amd64**, a chain of unresolved packets has led me to manually install **linux-libc-dev:amd64**, which has wiped out all the i386 dev support. Installing again **linux-libc-dev:i386** deleted the previously installed amd64 versions, but has left the system on an intermediate state where i386 architecture isn't working properly...

I'll do a clean lubuntu reinstall of a newer version (this was 15.04) and try again

**Comment by megamarc** [comment]
I've done a clean install of 32-bit Lubuntu 15.04, and installed the following packages:
```
dpkg --add-architecture amd64
apt-get update
apt-get install gcc-multilib
apt-get install libc6-dev:amd64
apt-get install libpng12-dev:amd64
```
Now the i386 and amd64 architectures coexist in peace, and I can build both without problems. However I'm having the following error when trying to install `libsdl2-dev:amd64`:
```
Los siguientes paquetes tienen dependencias incumplidas:
libsdl2-dev:amd64 : Depende: libegl1-mesa-dev:amd64 pero no va a instalarse
                     Depende: libgles2-mesa-dev:amd64 pero no va a instalarse
                     Depende: libmirclient-dev:amd64 pero no va a instalarse
                     Depende: libxkbcommon-dev:amd64 pero no va a instalarse
E: No se pudieron corregir los problemas, usted ha retenido paquetes rotos
```
In spanish, it complains about unresolved dependences that aren't going to be installed, and that I have broken packages. Is this the same issue you have?

**Comment by megamarc** [comment]
Good news in short: I have a working amd64 build of libTilengine.so and all the samples, that are working fine under a x64 lubuntu. I attach screenshot for proof.
Soon I'll make the official announcement, once I have packaged all in a new "linux64" target :-)

![tilengine_linux64](https://cloud.githubusercontent.com/assets/14149983/22057382/b3d71314-dd64-11e6-9dec-7cb98e0aea9c.png)

**Comment by davideGiovannini** [comment]
Yes that was the same issue,  I will try the x64 lib as soon as you release it :)

**Comment by megamarc** [comment]
Linux64 support is complete, commit done, download section of website updated and download package online

**Comment by davideGiovannini** [comment]
Works fine now ! :) 
If I manage to get it working well enough I will try to create a binding for rustlang
