### ISSUE TITLE
Support for Tiled animation?

### ISSUE THREAD

**Issue by devnewton** [megamarc/Tilengine#56]
Tiled provides an animation editor: https://doc.mapeditor.org/en/stable/manual/editing-tilesets/#tile-animation-editor

Are animated tiles in background supported by Tileengine?

Is there a way to load sprite sequence from a tmx map?

**Comment by megamarc** [comment]
Tile animations created in Tiled editor are supported in Tilengine. Just load a layer that has some animated tiles in its tileset, and they will be automatically assigned to free animation slots and played. No other action is required. The foreground tileset in `samples/assets/sonic/Sonic_md_fg1.tsx`, and the foreground layer in [PythonPlatformer](https://github.com/megamarc/TilenginePythonPlatformer) `assets/layer_foreground.tsx` have this feature. Just run them and you'll see the animations playing.

The animations reside in the tileset (tsx), not in the tilemap (tmx). You can use the function `TLN_GetTilesetSequencePack()` to obtain them, but this isn't usually needed.
