### ISSUE TITLE
CRT effect looks too dark

### ISSUE THREAD

**Issue by megamarc** [megamarc/Tilengine#57]
Historically my CRT effect keeps brightnes compared to unfiltered image. Release 2.2.0 (February 2019) shows correct behavior.

I've noticed that at least release 2.4.1 shows too dark image when filtered, brightness isn't conserved. I've built it with the 2.2.0 Window.c module (responsible of all window related things, including the CRT effect) but the brightness problem persist. Baffling, must investigate in depth because no other modules are involved.

**Comment by daltomi** [comment]
Hola @megamarc 
Lo siento, al parecer mi cambio en 2e06cca5cc8210f6f5cb48861b0b1cc79cbc4997 produce el issue.
![2019-12-22_scrot_000](https://user-images.githubusercontent.com/46515895/71323950-cae76980-24b7-11ea-90b5-55ddbbe0d6e5.png)


El commit justo anterior no lo hace: 027ea03b26e0089fadfcfe9ac9c8ad504fc8d816
![2019-12-22_scrot](https://user-images.githubusercontent.com/46515895/71323949-c9b63c80-24b7-11ea-8abf-b8c368395693.png)

**Comment by megamarc** [comment]
No es tu cambio, es un problema de alineación de una variable que debería ser `uint8_t` y era `bool`. Ya lo he solucionado en el commit [9351f91], gracias por mirarlo!

**Comment by daltomi** [comment]
Me alegra que lo hayas solucionado. Gracias!.
