### ISSUE TITLE
PNG requires redundant colours

### ISSUE THREAD

**Issue by danielgholmes** [megamarc/Tilengine#58]
We have a number of sprites that only have 8 colours, When trying to load the images I get an error `'Resource file has invalid format'`. We realised that if we add up to 32 redundant colours, it works. We are using Fireworks CS5 and it is a challenge having to always add redundant colours for every new image. Is there something we are missing here? Any suggestions on how we can work around this issue?

Here are two examples:

![shot_red_(32colors)](https://user-images.githubusercontent.com/8693754/71767148-b53f5e80-2f11-11ea-83af-d691d201241c.png)
32 colour palette image (working)

![shot_red_(8colors) ](https://user-images.githubusercontent.com/8693754/71767149-b53f5e80-2f11-11ea-8c12-6ed05b833f87.png)
8 colour palette image (causes error)

**Comment by daltomi** [comment]
It is expected. [Tilengine requires an 8-bit palette](https://github.com/megamarc/Tilengine/blob/9351f91f1745dfe82ce9728e3930677c157277a7/src/LoadBitmap.c#L52)

```
32-colour.png: PNG image data, 136 x 17, 8-bit colormap, non-interlaced
8-colour.png:  PNG image data, 136 x 17, 4-bit colormap, non-interlaced
```

**Comment by megamarc** [comment]
@daltomi is right: Tilengine loads 8-bpp indexed png's, no automatic color conversion is performed. This is not a bug.
