### ISSUE TITLE
Compiling on Mac.

### ISSUE THREAD

**Issue by shayneoneill** [megamarc/Tilengine#6]
I've been trying to get this thing porting on the mac. As an SDL project it should just compile with a few tweaks, but there seems to be a showstopper where its asking TileEngine.so *before* its compiled, which seems back to front, and I'm stumped as to how to fix it.

**Comment by megamarc** [comment]
@shayneoneill , you can't build **libTilengine.so** because the core is closed source, and I haven't released binaries for Mac yet. Sorry!

**Comment by shayneoneill** [comment]
Wouldnt it just be easier to include the sources and let the community sort it out?

**Comment by megamarc** [comment]
Tilengine is coming to OS X. So far I’ve installed OS X Mountain Lion (10.8) inside a VMWare virtual machine, installed libSDL2 framework, installed command-line tools for Xcode, and built libpng from source. I still have some minor issue building the Tilengine shared library but the final product is near.

Once it’s done, I’ll have to research how to install development libraries in OS X. Any information is welcome because I’m not a Mac user at all.

![tilengine_osx](https://cloud.githubusercontent.com/assets/14149983/22183434/76a929c0-e0be-11e6-93eb-4bc1b53d9906.jpg)

**Comment by megamarc** [comment]
**OS X support completed**
I've successfully built Tilengine library and run all the samples under OS X, here I attach a screenshot for proof. Now I just have to learn what are best practices in OS X to distribute and install shared development libraries and headers, and then I'll do a public release.
**Apple devs**: any guideline is welcome.

![tilengine_osx_ok](https://cloud.githubusercontent.com/assets/14149983/22198447/d8e315f4-e156-11e6-8a2c-73297a3e0479.jpg)

**Comment by shayneoneill** [comment]
Generally speaking theres two ways to do it. You can include a .so as you normally would for linux, or you can create a .dylib framework. .dylib , like mac apps are pseudo-file directories you can stuff headers and the like into which makes them rather pleasant to work with in Xcode, and you can do a few fancy tricks like put multiple architectures (aka "fat binaries") in the same binary file, for instance including an IOS and OSX version together. And so on. 

If I can figure out how to drive private message on this thing, I'll send you my email address and I can do testing on my box, if you wish, and let you know how far off target you are.

**Comment by shayneoneill** [comment]
Ok, looks like there isn't a way to send you a private message on github. My email is shayne dot oneill at gmail . If you want me to review your packaging , blast me a message there and I'll see how I can help.

**Comment by megamarc** [comment]
macOS update is complete. User must ensure that SDL2 is installed and **/usr/local/*** directories are include and binary searchable because the install script puts the SDK files there.
