### ISSUE TITLE
How easy/hard to make this run on 8 bit machine?

### ISSUE THREAD

**Issue by bootrino** [megamarc/Tilengine#76]
I'd like to use something like this to run on an 8 bit machine.

How hard/easy/impossible would that be?

Essentially I'd need to be able to create an application that fits into say 52K in total and embeds its tiles/sprites into the application code.

Any thoughts appreciated.

**Comment by megamarc** [comment]
Sorry, there's no way to have something comparable to tilengine in an 8-bit machine. If 8-bit CPU and 52 kb are real constraints, you need to lower expectations quite a bit. Target an 8-bit machine with a capable VDP -research on MSX2, NEC PC-Engine or ZX Spectrum Next-. But even on them, being the most graphically advanced 8-bit machines developed, you'll be severely restricted compared to 16-bit platforms. Tilengine kind of emulates and extends VDPs of the 16-bit era in software, but requires a 32-bit CPU to run.
