### ISSUE TITLE
Tilengine without Tiled/TMX

### ISSUE THREAD

**Issue by metasprite** [megamarc/Tilengine#81]
I use my own custom, highly-compressed binary level format and a custom level editor. This is needed because the game is designed around user-generated content, and disk space isn't free. Levels can still be *ridiculously* large, so my game will load and unload screens on the fly based on what's in view.

I read on the forum that "Tilengine is quite tied to tmx (Tiled) format," so I'd like to know if this will be a problem before I commit to integrating it into my engine. If there's either A. a workaround (some way to feed it binary data) or B. a reasonable possibility of modifying the source myself (i.e. wouldn't require a full rewrite of the tile renderer) then it's fine, otherwise I'll unfortunately have to pass and continue painfully writing my own.

**Comment by megamarc** [comment]
Hi @metasprite,

Tilengine loaders can read some .tmx/.tsx/ files out of the box, but it doesn't mean you aren't allowed to use any arbitrary storage format. Tilengine provides some functions to create data assets at runtime, ideal for implementing procedural data or custom loaders. In fact the built-in Tiled loaders first prepare data and then call those same generators that you'll need to call yourself with custom data.

To create **Tilesets**: check **TLN_CreateTileset()** and **TLN_SetTilesetPixels()**. Use source code of **TLN_LoadTileset()** as a reference implementation of custom loader.
http://www.tilengine.org/doc/group__tileset.html

To create **Tilemaps**: check **TLN_CreateTilemap()** and optionally **TLN_SetTilemapTile()**. Use source code of **TLN_LoadTilemap()** as a reference implementation of custom loader.
http://www.tilengine.org/doc/group__tilemap.html

To create **Bitmaps**: check **TLN_CreateBitmap()** and **TLN_GetBitmapPtr()**. Use source code of **TLN_LoadBitmap()** as a reference implementation of custom loader.
http://www.tilengine.org/doc/group__bitmap.html

I don't know your custom format, but keep in mind that you can only load data that is already supported by the engine.

Let me know

**Comment by metasprite** [comment]
This seems good, thank you. It's just that the phrasing made me think the internal format might be based on tmx.
