### ISSUE TITLE
libretro port

### ISSUE THREAD

**Issue by kivutar** [megamarc/Tilengine#83]
Hi, this is a nice project!

Have you ever consider a libretro port of it?

It would allow to run the games on a very wide range of consoles and platforms.

**Comment by kivutar** [comment]
I just found the libretro branch... :D

**Comment by megamarc** [comment]
Hi! Thanks for your words :-)
Libretro port isn't updated to latest engine release, but it works. It's somewhat different than the main project. With libretro it works like an "emulator core", where a single core can load many games. In this case, it has LUA embedded on it, so you have to write your games in lua, and let the core load and run them.
