### ISSUE TITLE
Sprite not drawn after calling TLN_SetNextSprite

### ISSUE THREAD

**Issue by danielgholmes** [megamarc/Tilengine#84]
In the game I am making I have ground sprites, flying sprites, and sprites that are part of the game HUD. Each should be drawn in that order. Ground and flying sprites are spawned under certain conditions, and as such, some reordering of sprite drawing order needs to take place. I cannot rely on drawing order based on when each sprite is created as each new sprite is drawn on top of older ones, and so I need to use `TLN_SetNextSprite`.

I am able to change the sprite drawing order without any issues when calling `TLN_SetNextSprite(sprite, next)` . However, after calling that method and then drawing a completely new sprite, the `next` sprite from the call above disappears i.e. it appears to be no longer drawn.

Below is an example of some Python code using the latest version of Tilengine and the bindings that simulates the issue. At frame 100, a new flying sprite is created and the drawing order is changed and it works as expected. At frame 200, I create a new ground unit, which then causes the `hud_sprite` to disappear. Note that it is not disabled as `state.enabled` returns `True` even after frame 200.

Am I doing something incorrectly or is this is some kind of bug?

```python
import os

os.add_dll_directory(os.getcwd())

from tilengine import *

engine = Engine.create(480, 270, 1, 4, 0)
window = Window.create()
window.disable_crt_effect()
engine.set_log_level(LogLevel.VERBOSE)

ground_sprite1 = engine.sprites[0]
ground_sprite1.setup(Spriteset.fromfile("ground"))

hud_sprite = engine.sprites[1]
hud_sprite.setup(Spriteset.fromfile("hud"))
hud_sprite.set_flags(Flags.PRIORITY)

while window.process():
    hud_sprite.set_position(0, 0)
    ground_sprite1.set_position(0, 0)

    if window.num_frame == 100:
        flying_sprite = engine.sprites[2]
        flying_sprite.setup(Spriteset.fromfile("flying"))
        flying_sprite.set_flags(Flags.PRIORITY)
        flying_sprite.set_position(0, 0)
        flying_sprite.set_next(hud_sprite)

    if window.num_frame == 200:
        ground_sprite2 = engine.sprites[3]
        ground_sprite2.setup(Spriteset.fromfile("ground"))
        ground_sprite2.set_position(20, 0)

    state = SpriteState()
    hud_sprite.get_state(state)
    print(state.enabled)
```

**Comment by megamarc** [comment]
Hi Daniel,
I'm investigating it. Having a full sample source that reproduces the issue helps a lot! I'll tell you when I find the cause

**Comment by danielgholmes** [comment]
Hi Marc,

Thanks so much for the quick fix! It's all working as expected on my side now.
