### ISSUE TITLE
Compiling problem

### ISSUE THREAD

**Issue by ChuiDC** [megamarc/Tilengine#9]
There are lots of undefined references when compiling samples after the library.

Is the repository completed?

It seems lack some sources in src_lib directory because some TLN_xxxxx implementation calls cannot be found, e.g. TLN_CreateSpriteset

$ make -f Makefile_linux64 
gcc Barrel.o Simon.o -o ../bin/barrel -lTilengine -lm -s -L../lib/linux64/
Barrel.o: In function `LoadLayer':
Barrel.c:(.text+0x8d): undefined reference to `TLN_SetLayer'
Barrel.o: In function `raster_callback':
Barrel.c:(.text+0x127): undefined reference to `TLN_SetLayerAffineTransform'
Barrel.c:(.text+0x146): undefined reference to `TLN_SetLayerPalette'
Barrel.c:(.text+0x17c): undefined reference to `TLN_SetLayerPalette'
Barrel.c:(.text+0x1a3): undefined reference to `TLN_SetLayerPalette'
Barrel.o: In function `main':
Barrel.c:(.text.startup+0x2b): undefined reference to `TLN_Init'
Barrel.c:(.text.startup+0x38): undefined reference to `TLN_SetRasterCallback'
Barrel.c:(.text.startup+0x4c): undefined reference to `TLN_SetBGColor'
Barrel.c:(.text.startup+0x82): undefined reference to `TLN_GetTilesetPalette'
Barrel.c:(.text.startup+0x91): undefined reference to `TLN_ClonePalette'
Barrel.c:(.text.startup+0xaf): undefined reference to `TLN_GetPaletteData'
Barrel.c:(.text.startup+0x164): undefined reference to `TLN_SetLayerPosition'
Barrel.c:(.text.startup+0x173): undefined reference to `TLN_SetLayerPosition'
Barrel.c:(.text.startup+0x19f): undefined reference to `TLN_DeleteTileset'
Barrel.c:(.text.startup+0x1ab): undefined reference to `TLN_DeleteTilemap'
Barrel.c:(.text.startup+0x1b7): undefined reference to `TLN_DeleteTileset'
Barrel.c:(.text.startup+0x1c3): undefined reference to `TLN_DeleteTilemap'
Barrel.c:(.text.startup+0x1cd): undefined reference to `TLN_Deinit'
Simon.o: In function `SimonDeinit':
Simon.c:(.text+0xc): undefined reference to `TLN_DeleteSequencePack'
Simon.o: In function `SimonSetState':
Simon.c:(.text+0x4b): undefined reference to `TLN_DisableAnimation'
Simon.c:(.text+0x57): undefined reference to `TLN_SetSpritePicture'
Simon.c:(.text+0x71): undefined reference to `TLN_DisableAnimation'
Simon.o: In function `SimonInit':
Simon.c:(.text+0xcf): undefined reference to `TLN_FindSequence'
Simon.c:(.text+0xe4): undefined reference to `TLN_SetSpriteSet'
Simon.c:(.text+0xf7): undefined reference to `TLN_SetSpritePosition'
Simon.o: In function `SimonTasks':
Simon.c:(.text+0x1db): undefined reference to `TLN_GetLayerTile'
Simon.c:(.text+0x216): undefined reference to `TLN_SetSpritePosition'
Simon.c:(.text+0x377): undefined reference to `TLN_SetSpriteFlags'
Simon.c:(.text+0x392): undefined reference to `TLN_SetSpriteFlags'
Simon.o: In function `SimonDeinit':
Simon.c:(.text+0x1c): undefined reference to `TLN_DeleteSpriteset'
Simon.o: In function `SimonSetState':
Simon.c:(.text+0x7e): undefined reference to `TLN_SetSpritePicture'
Simon.c:(.text+0x9a): undefined reference to `TLN_SetSpriteAnimation'
../lib/linux64//libTilengine.so: undefined reference to `TLN_CreateCycle'
../lib/linux64//libTilengine.so: undefined reference to `TLN_DrawNextScanline'
../lib/linux64//libTilengine.so: undefined reference to `TLN_SetTilesetPixels'
../lib/linux64//libTilengine.so: undefined reference to `TLN_CreateBitmap'
../lib/linux64//libTilengine.so: undefined reference to `TLN_SetRenderTarget'
../lib/linux64//libTilengine.so: undefined reference to `TLN_CreateSpriteset'
../lib/linux64//libTilengine.so: undefined reference to `TLN_SetPaletteColor'
../lib/linux64//libTilengine.so: undefined reference to `TLN_CreateTileset'
../lib/linux64//libTilengine.so: undefined reference to `TLN_GetBitmapPitch'
../lib/linux64//libTilengine.so: undefined reference to `TLN_GetBitmapWidth'
../lib/linux64//libTilengine.so: undefined reference to `TLN_GetHeight'
../lib/linux64//libTilengine.so: undefined reference to `TLN_DeleteBitmap'
../lib/linux64//libTilengine.so: undefined reference to `TLN_SetBitmapPalette'
../lib/linux64//libTilengine.so: undefined reference to `TLN_GetBitmapPtr'
../lib/linux64//libTilengine.so: undefined reference to `TLN_GetWidth'
../lib/linux64//libTilengine.so: undefined reference to `TLN_SetLastError'
../lib/linux64//libTilengine.so: undefined reference to `TLN_GetBitmapPalette'
../lib/linux64//libTilengine.so: undefined reference to `TLN_BeginFrame'
../lib/linux64//libTilengine.so: undefined reference to `TLN_CreateSequencePack'
../lib/linux64//libTilengine.so: undefined reference to `TLN_CreateTilemap'
../lib/linux64//libTilengine.so: undefined reference to `TLN_CreateSequence'
../lib/linux64//libTilengine.so: undefined reference to `SelectBlendTable'
../lib/linux64//libTilengine.so: undefined reference to `TLN_GetBitmapHeight'
../lib/linux64//libTilengine.so: undefined reference to `TLN_CreatePalette'
../lib/linux64//libTilengine.so: undefined reference to `TLN_SetTilemapTile'
../lib/linux64//libTilengine.so: undefined reference to `TLN_AddSequenceToPack'
../lib/linux64//libTilengine.so: undefined reference to `TLN_GetBitmapDepth'
../lib/linux64//libTilengine.so: undefined reference to `TLN_UpdateFrame'

**Comment by megamarc** [comment]
Tilengine source code is partially closed. The provided sources in the src_lib folder are meant to be used as reference implementations of shell functionality (framework integration and file loaders/parsers) but they're not enough to build the library. The rendering core is not publicly available, as stated in the src_lib/readme.txt file.
