### ISSUE TITLE
Map layer with multiple .tsx files causes memory issues

### ISSUE THREAD

**Issue by danielgholmes** [megamarc/Tilengine#98]
There are some levels in our game that use a combination of tilesets (`.tsx`) files for a given layer. But what I've noticed that if I try to include a layer with more than one `.tsx` file then there are memory issues. 

For example, sometimes the game just crashes immediately, and other times the game runs, but the completely wrong tile is shown. This immediately looks like a memory issue.

Notice below how I have `city1.tsx` and `mech1.tsx` in the same layer in a `.tmx` file. But when I run the game, the game window shows the wrong tile from the wrong tileset, or just no tile at all.

Does a layer in Tilengine only support a single associated `.tsx` file? Based on what I see in the Tilengine code, a layer should be able to support multiple `.tsx` files. 

![Screenshot 2022-09-01 183301](https://user-images.githubusercontent.com/8693754/187967183-3e6883a3-8720-48d3-9b8e-27b564f19b1a.png)
![Screenshot 2022-09-01 183330](https://user-images.githubusercontent.com/8693754/187967192-522e400d-e61c-44f4-a535-2a26ef700e7a.png)
![Screenshot 2022-09-01 183356](https://user-images.githubusercontent.com/8693754/187967194-1aa0308d-d7e5-4c60-afc4-974fa6112fc2.png)

**Comment by megamarc** [comment]
Hi Daniel,
Tilengine doesn't support multiple simultaneous tilesets per layer. Tiled editor lets you create maps with this scheme, but Tilengine doesn't implement this feature. All tiles used in a layer should be packed into a single tileset. The documentation always refers to the tileset in a layer in singular, and doesn't provide any API function to manage a collection of tilesets.
Sorry for the inconvenience. I should state this constraint more clearly in the documentation.
