### ISSUE TITLE
TLN_GetTilemapTileset2 returns None/NULL

### ISSUE THREAD

**Issue by danielgholmes** [megamarc/Tilengine#99]
I'm busy trying out the latest version of Tilengine, but I'm having issues with loading tilemaps.

Using Python bindings, I'm trying the following with my existing maps:

```Python
from tilengine import Engine, Window, Tilemap

engine = Engine.create(400, 240, 1, 0, 20)
engine.set_load_path("assets")
foreground = Tilemap.fromfile("map01.tmx", layer_name="foreground1")
engine.layers[0].setup(foreground)

window = Window.create()
while window.process():
    window.draw_frame()
```

The constructor for creating the foreground `Tilemap` looks like this in the Python bindings:

```Python
class Tilemap(object):
	"""
	The Tilemap object holds the grid of tiles that define the background layout

	:ivar rows: number of rows (vertical cells)
	:ivar cols: number of columns (horizontal cells)
	:ivar tileset: Tileset object attached inside the resource file
	"""
	def __init__(self, handle: c_void_p, owner: bool=True):
		self._as_parameter_ = handle
		self.owner = owner
		self.library = _tln
		self.rows = _tln.TLN_GetTilemapRows(handle)
		self.cols = _tln.TLN_GetTilemapCols(handle)
		tileset_handle = _tln.TLN_GetTilemapTileset2(handle, 0)
		if tileset_handle is not None:
			self.tileset = Tileset(tileset_handle, False)
		else:
			self.tileset = None
```
 When debugging, I noticed that the `tileset_handle` always comes back as None/NULL, so the issues appears to be with the new `TLN_GetTilemapTileset2` function.

I'm also a bit confused because shouldn't the tilemap have multuiple tilesets, based on this recent update? In the latest commit message it says:

> * tmx files with multiple tilesets per layer are automatically loaded, no need to use new API functions

So am I right in saying `TLN_GetTilemapTileset2` doesn't need to be called in the constructor?

**Comment by megamarc** [comment]
Hi Daniel,
Thanks for trying the new features :-)

I've debugged your issue, but with my test assets it works as expected.

Here I attach a small test with source code and related assets. I haven't attached Tilengine.dll/.so itself as I don't know your target platform, but I've tested it with release 2.11.
[test_py.zip](https://github.com/megamarc/Tilengine/files/9793679/test_py.zip)

It's a small test that loads `layer_tilemap.tmx` that contains tiles from two separate tilesets, and then print their internal handles to console. You should see something like this:

```
./python test.py
Tilengine v2.11.0 64-bit built Oct  2 2022 10:24:38
tileset 0 = 2697139834032
tileset 1 = 2697139585152
```

If this works for you too, then there's something in the structures of your assets. In that case, I should test them to see what's going on.

Regarding the commit message, multiple tilesets are automatically loaded and stored as references inside the tilemap, you don't need to do anything else. `TLN_GetTilemapTileset2` has subsumed previous `TLN_GetTilemapTileset` and is just a convenience function to retrieve selected tileset, in case you need to manipulate it in realtime or query some of its properties. The `Tilemap` constructor calls it for convenience -it's more pythonic to have a public property than having to call a method to get an opaque value-. You could safely remove it from the constructor and the tilesets would still work perfectly as they're loaded and linked internally, but you won't get the `tileset` convenience property.

I hope this explanation makes the issue more clear, and let me know the results of the attached test.

**Comment by danielgholmes** [comment]
Hi Marc,

Thanks for your quick response. I managed to get your sample working without an issue. However, when trying to get my existing maps to work, it brought to surface another issue with TMX files.

Using the below code, I try and draw a frame:

```python
from tilengine import Engine, Tilemap, Window

engine = Engine.create(400, 240, 2, 0, 20)

engine.set_load_path("assets")
foreground = Tilemap.fromfile("map05.tmx", layer_name="Tile Layer 1")

engine.layers[0].setup(foreground)
window = Window.create()

while window.process():
    window.draw_frame()
```

But `window.draw_frame()` results in the following error: 

> _tln.TLN_UpdateFrame(num_frame)
> OSError: exception: access violation reading 0x0000000000000068 

You can get the map and tileset I tested it on here: [example.zip](https://github.com/megamarc/Tilengine/files/9857745/example.zip)

The problem appears to be the order in which the tileset is referenced in the TMX file. If `Tile Layer 1` uses a specific tileset, then that tileset has to be at the top of the list where the tilesets are referenced in the `<tileset />` XML tag. In the example I uploaded, if you manually put `<tileset firstgid="1" source="test.tsx"/>` before `<tileset firstgid="6" source="area.tsx"/>` and then save it in Tiled, then the above code, the error goes away.

The problem with this is that it's quiet difficult to manually change the order of the tilesets in the TMX file, especially in the case where we have quite a number of tilesets, and when tilesets are being added and removed while maps are being built. Secondly, I noticed that Tiled does not remove a reference to a tileset if it is no longer used in the map; it just stays there in a  `<tileset firstgid="6" source="area.tsx"/>`. Again, the workaround is having to manually edit the TMX file.

Another issue I noticed is that Tilengine throws a `tilengine.TilengineException: 'Invalid Tileset reference'` error if there is a map layer that has no tiles associated with it. This isn't such a big deal, but you can just add a single tile somewhere to the layer, but it's not obvious what the error is, especially seeing as previous versions of Tilengine did make allowances for completely empty layers.

Seems like this is a related, if not the same issue: https://tilengine.org/forum/showthread.php?tid=2275

**Comment by megamarc** [comment]
Hi Daniel,

Yes you're right. The last multi-tileset implementation is still a bit buggy, on the surface it's easy to implement but it has some unforeseen consequences about how Tiled arranges tilesets. It's the same issue you point out in the forums. My test cases when I released the feature were "ideal cases" so I didn't detected these quirks, but with your test cases I'm working on a fix that I hope to release soon. There's even a Pull Request here on GitHub with a possible fix that I have to test. This fix should allow to tolerate unordered and/or unused tilesets. Having you to alter by hand the tmx file isn't the way to go.

By the way, how many actual tilesets per layer are you targeting? I mean, used tilesets, not counting the ones referenced but not used.

There's another issue that has been detected with the multi-tileset feature. In short words: right now the engine doesn't properly handle colour when each tileset on a layer uses its own palette, multi-palettes per layer aren't supported. Providing a quick fix breaks palette raster effects, that is a core and disctintive feature of Tilengine, so at the moment I've left it unfixed.

However I'm actively working on a development branch, reworking and cleaning core parts of the rendering engine that will allow to have multiple palettes per layer without breaking the color raster effects.

First I'll release the fix for the multi-tileset issue, and later the fix for palettes.

Sorry for the inconvenience and thanks for the test cases!

**Comment by danielgholmes** [comment]
Hi Marc,

For now we have 2 tilesets per map layer, but at most it will be 3. The other tilesets which are referenced in the TMX file are on object layers for enemies and other game entities. But those object layers are read directly from the XML. We don't have any raster effects at the moment, so the palette issue hasn't come up.

Thanks again for your prompt help in fixing the issues!

**Comment by danielgholmes** [comment]
So after some testing it seems a palette issue has come up, but I'll wait for your fix. I'll close this ticket for now seeing as the original issue has been solved.
